#!/usr/bin/env python3
"""Generate rtl/<test>/tb_computer.sv for the accel_mac_p1 variant.

The CWB REG pragma (R1.W1, 4096 entries) produces 4096 individual
dmem_arg_rg<N>_{rd,wd,we} ports that must all be wired in the testbench.
"""

DMEM_SIZE = 4096
IMEM_SIZE = 65536
CLK_PERIOD = 10

def rg(n):
    """Format register index to match CWB port naming: 2-digit min, no extra padding."""
    return f"{n:02d}" if n < 100 else str(n)

out = []
w = out.append

w("// ============================================================================")
w("// Testbench for HLS-generated RV32I computer module")
w("// Instantiates imem (ROM) and dmem (REG, R1.W1, 4096 entries) and connects")
w("// to the computer. Loads a .hex file via +HEX_FILE plusarg and runs until halt.")
w("//")
w("// This file is auto-generated — do not edit by hand.")
w("// Regenerate: python3 scripts/gen_tb_<test>.py > rtl/<test>/tb_computer.sv")
w("//")
w("// Usage (Verilator):")
w("//   ./obj_dir/tb_computer_sim +HEX_FILE=/path/to/program.hex")
w("// ============================================================================")
w("")
w("`timescale 1ns / 1ps")
w("")
w("module tb_computer;")
w("")
w("`ifndef PC_SIG")
w("  `define PC_SIG RG_addr_addr1_PC")
w("`endif")
w("")
w("  // --------------------------------------------------------------------------")
w("  // Parameters")
w("  // --------------------------------------------------------------------------")
w(f"  parameter IMEM_SIZE  = {IMEM_SIZE}; // 64K words")
w(f"  parameter DMEM_SIZE  = {DMEM_SIZE};  // 4K words")
w("  parameter ADDR_BITS  = 16;")
w(f"  parameter CLK_PERIOD = {CLK_PERIOD};     // 10 ns -> 100 MHz (matches -c1000 = 10ns)")
w("")
w("  // --------------------------------------------------------------------------")
w("  // Signals")
w("  // --------------------------------------------------------------------------")
w("  reg         clk;")
w("  reg         rst;")
w("")
w("  // IMEM interface (read-only ROM)")
w("  wire        imem_re;")
w("  wire [ADDR_BITS-1:0] imem_addr;")
w("  reg  [31:0] imem_rdata;")
w("")
w("  // Halt output")
w("  wire        halt;")
w("")
w("  // --------------------------------------------------------------------------")
w("  // Memories")
w("  // --------------------------------------------------------------------------")
w("  reg [31:0] imem [0:IMEM_SIZE-1];")
w("  reg [31:0] dmem [0:DMEM_SIZE-1];")
w("")
w("  // IMEM read (synchronous, 1-cycle latency)")
w("  always @(posedge clk) begin")
w("    if (imem_re)")
w("      imem_rdata <= imem[imem_addr];")
w("  end")
w("")
w("  // --------------------------------------------------------------------------")
w("  // DMEM REG interface: 4096 individual rd/wd/we ports (R1.W1)")
w("  // --------------------------------------------------------------------------")
for n in range(DMEM_SIZE):
    r = rg(n)
    w(f"  wire [31:0] dmem_arg_rg{r}_rd;")
    w(f"  wire [31:0] dmem_arg_rg{r}_wd;")
    w(f"  wire        dmem_arg_rg{r}_we;")

w("")
w("  // Drive read-port data from TB dmem array into DUT inputs")
for n in range(DMEM_SIZE):
    r = rg(n)
    w(f"  assign dmem_arg_rg{r}_rd = dmem[{n}];")

w("")
w("  // Capture write-port: update dmem when DUT asserts a register write enable")
w("  always @(posedge clk) begin")
for n in range(DMEM_SIZE):
    r = rg(n)
    w(f"    if (dmem_arg_rg{r}_we) dmem[{n}] <= dmem_arg_rg{r}_wd;")
w("  end")

w("")
w("  // --------------------------------------------------------------------------")
w("  // DUT Instantiation")
w("  // --------------------------------------------------------------------------")
w("  computer dut (")
w("    .imem_arg_MEMB32W65536_RE1      (imem_re),")
w("    .imem_arg_MEMB32W65536_RA1      (imem_addr),")
w("    .imem_arg_MEMB32W65536_RD1      (imem_rdata),")
w("")
for n in range(DMEM_SIZE):
    r = rg(n)
    w(f"    .dmem_arg_rg{r}_rd           (dmem_arg_rg{r}_rd),")
    w(f"    .dmem_arg_rg{r}_wd           (dmem_arg_rg{r}_wd),")
    w(f"    .dmem_arg_rg{r}_we           (dmem_arg_rg{r}_we),")
w("")
w("    .computer_ret                    (halt),")
w("    .CLOCK                           (clk),")
w("    .RESET                           (rst)")
w("  );")

w("")
w("  // --------------------------------------------------------------------------")
w("  // Debug Signals (CPU integer register file)")
w("  // --------------------------------------------------------------------------")
w("  wire [31:0] shadow_regs [0:31];")
for i in range(32):
    w(f"  assign shadow_regs[{i:2d}] = dut.INST_dat.regs_rg{i:02d};")

w("")
w("  // --------------------------------------------------------------------------")
w("  // Clock Generation")
w("  // --------------------------------------------------------------------------")
w("  initial clk = 0;")
w("  always #(CLK_PERIOD / 2) clk = ~clk;")
w("")
w("  // --------------------------------------------------------------------------")
w("  // Main Test Sequence")
w("  // --------------------------------------------------------------------------")
w("  integer cycle_count;")
w("  integer max_cycles = 10000000;")
w("")
w("  // Report file handle (optional, via +RPT_FILE=...)")
w("  integer rpt_fd;")
w("  string  rpt_file;")
w("")
w("  // Combined memory for loading hex (imem + dmem concatenated)")
w("  reg [31:0] full_mem [0:IMEM_SIZE+DMEM_SIZE-1];")
w("")
w("  // Hex file path from plusarg")
w("  string hex_file;")
w("")
w("  // FST trace file path (optional, via +FST_FILE=...)")
w("  string fst_file;")
w("")
w("  initial begin")
w('    // Get hex file path from +HEX_FILE=... plusarg')
w('    if (!$value$plusargs("HEX_FILE=%s", hex_file)) begin')
w('      $display("ERROR: No hex file specified. Use +HEX_FILE=/path/to/file.hex");')
w('      $finish;')
w('    end')
w("")
w('    // Optional report file')
w('    rpt_fd = 0;')
w('    if ($value$plusargs("RPT_FILE=%s", rpt_file)) begin')
w('      rpt_fd = $fopen(rpt_file, "w");')
w('      if (rpt_fd == 0) begin')
w('        $display("WARNING: Could not open report file: %s", rpt_file);')
w('      end')
w('    end')
w("")
w('    // Load combined hex: first 65536 words = imem, rest = dmem')
w('    $readmemh(hex_file, full_mem);')
w('    for (int i = 0; i < IMEM_SIZE; i++) begin')
w('      imem[i] = full_mem[i];')
w('    end')
w('    for (int i = 0; i < DMEM_SIZE; i++) begin')
w('      dmem[i] = full_mem[i + IMEM_SIZE];')
w('    end')
w('    $display("Loaded hex: %s", hex_file);')
w('    $display("  First 6 imem words:");')
w('    for (int i = 0; i < 6; i++)')
w('      $display("    imem[%0d] = 0x%08h", i, imem[i]);')
w("")
w('    // Reset sequence')
w("    rst = 1;")
w("    imem_rdata = 32'h0;")
w("    repeat (5) @(posedge clk);")
w("    rst = 0;")
w("")
w('    $display("\\n=== RTL Simulation Start ===");')
w("")
w("    // Optional FST tracing (enabled via make TRACE=1)")
w("    `ifdef TRACE_EN")
w('      if (!$value$plusargs("FST_FILE=%s", fst_file))')
w('        fst_file = "trace.fst";')
w('      $dumpfile(fst_file);')
w('      $dumpvars(0, tb_computer);')
w('      $display("  FST tracing enabled -> %s", fst_file);')
w("    `endif")
w("")
w("    // Run until halt or max_cycles")
w("    cycle_count = 0;")
w("    while (!halt && cycle_count < max_cycles) begin")
w("      @(posedge clk);")
w("      cycle_count++;")
w("    end")
w("")
w("    if (!halt)")
w('      $display("WARNING: max_cycles (%0d) reached without halt!", max_cycles);')
w("")
w('    $display("\\n=== RTL Simulation Complete ===");')
w('    $display("  Total cycles: %0d", cycle_count);')
w('    $display("  Status: %s", halt ? "HALTED" : "TIMEOUT");')
w("")
w("    // Dump registers (matching sim_cpu.rpt format)")
w('    $display("\\n=== Register Dump ===");')
w('    for (int i = 0; i < 32; i += 8) begin')
w('      $write("  ");')
w('      for (int j = 0; j < 8 && (i+j) < 32; j++)')
w('        $write("x%02d: %08h ", i+j, shadow_regs[i+j]);')
w('      $display("");')
w('    end')
w("")
w("    // Dump first 8 dmem words")
w('    $display("\\n=== DMEM Dump (first 8 words) ===");')
w('    for (int i = 0; i < 8; i++)')
w('      $display("  dmem[%0d] = 0x%08h", i, dmem[i]);')
w("")
w("    // Write report file if requested")
w("    if (rpt_fd != 0) begin")
w('      $fwrite(rpt_fd, "=== RTL Simulation Report ===\\n");')
w('      $fwrite(rpt_fd, "Hex file: %s\\n", hex_file);')
w('      $fwrite(rpt_fd, "Total cycles: %0d\\n", cycle_count);')
w('      $fwrite(rpt_fd, "Status: %s\\n", halt ? "HALTED" : "TIMEOUT");')
w('      $fwrite(rpt_fd, "\\n=== Register Dump ===\\n");')
w('      for (int i = 0; i < 32; i += 8) begin')
w('        for (int j = 0; j < 8 && (i+j) < 32; j++)')
w('          $fwrite(rpt_fd, "x%02d: %08h ", i+j, shadow_regs[i+j]);')
w('        $fwrite(rpt_fd, "\\n");')
w('      end')
w('      $fwrite(rpt_fd, "\\n=== DMEM Dump (first 8 words) ===\\n");')
w('      for (int i = 0; i < 8; i++)')
w('        $fwrite(rpt_fd, "dmem[%0d] = 0x%08h\\n", i, dmem[i]);')
w('      $fclose(rpt_fd);')
w('      $display("\\nReport written to: %s", rpt_file);')
w('    end')
w("")
w('    $display("\\n=== Done ===");')
w("    $finish;")
w("  end")
w("")
w("endmodule")

print("\n".join(out))
